# Detecção de Profissões
O objetivo do exercício é criar um classificador capaz de reconhecer a profissão do solicitante com base na requisição recebida. Utiliza-se um conjunto de dados o qual contém o conteúdo da requisição e a profissão do emissor. As categorias consideradas pela classe alvo são: **governament**, **private** e **academic**

In [1]:
# importação de bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Importando conjunto de dados ***"ep2-train.csv"***

In [4]:
path_file = "../ep2-train.csv"
df = pd.read_csv(path_file, encoding='latin1', sep=';')

In [5]:
df.head()

                                            req_text  profession
0  Sou aluna de doutorado da UFPR e pesquiso sobr...    academic
1  Gostaria de consultar a disponibilidade de cód...    academic
2  Prezados, bom dia. Procurei no site do Serpro ...  government
3  Solicito o número de matrícula do SIAP do doce...    academic
4  A Lei nº 12772/2012 regulamenta a carreira de ...    academic

In [6]:
df['profession'].value_counts()

profession
government    18782
academic      14593
private       10303
Name: count, dtype: int64

Como é possível visualizar, ***"ep2-train.csv"*** é um conjunto desbalanceado, contendo majoritariamente requisições de pessoas do **governo**. Logo, a acurácia não é uma métrica confiável para avaliar o desempenho do classificador.

In [9]:
df.isnull().sum()

req_text      0
profession    0
dtype: int64

In [10]:
df.duplicated().sum()

6898

O conjunto possui algumas instâncias **repetidas**, mas não há dados **faltantes**. Pode haver requisições iguais com profissões distintas, porém isso será mantido, visto que não como decidir qual é a profissão correta e uma exclusão simples poderia acarretar em uma perda **significativa** de dados. Logo, será retirado apenas as instâncias repetidas considerado todas as **colunas**.

In [11]:
df = df.drop_duplicates() # retira instâncias duplicadas

In [12]:
df.duplicated().sum()

0

Será aplicado uma transformação **One-hot Encoding** sobre ***"profession"***, por se tratar de uma coluna categórica nominal. Retira-se uma coluna para evitar o fenômeno da **Multicolinearidade Perfeita**.

In [13]:
df_encoded = pd.get_dummies(df, columns=['profession'], drop_first=True) # transformação One-Hot Encoding

In [14]:
df_encoded.head()

,req_text,profession_government,profession_private
0,Sou aluna de doutorado da UFPR e pesquiso sobr...,False,False
1,Gostaria de consultar a disponibilidade de cód...,False,False
2,"Prezados, bom dia. Procurei no site do Serpro ...",True,False
3,Solicito o número de matrícula do SIAP do doce...,False,False
4,A Lei nº 12772/2012 regulamenta a carreira de ...,False,False

## Modelagem da Representação Textual

Com base em experiências passadas, será apenas explorado o impacto da ***representação textual***, pois se viu que o algoritmo utilizado pouco influencia o desempenho. O desempenho é determinado **majoritamente** pela representação utilizada.

In [7]:
#Bag-of-words
from sklearn.feature_extraction.text import CountVectorizer

vect = CountVectorizer()
X = vect.fit_transform(df['req_text']) # BoW com frequência normalizada

In [8]:
X.shape

(43678, 67761)